---

- name: "change user quota Playbook"
  hosts: localhost
  gather_facts: no
  tasks:
    
    - name: "load configs"
      include_vars:
        file: data/config.yml
        name: configs

    - name: "load args"
      include_vars:
        file: "data/args.json"
        name: args

    - name: "looping role change_quota"
      include_role:
        name: change_quota
      vars:
        user: "{{ item }}"
      with_items:
        - "{{ args.users }}"
