---

- name: "create user Playbook"
  hosts: localhost
  gather_facts: no
  tasks:
    
    - name: "load configs"
      include_vars:
        file: data/config.yml
        name: configs

    - name: "load args"
      include_vars:
        file: "data/args.json"
        name: args

    - name: "looping role remove_user"
      include_role:
        name: remove_user
      vars:
        user: "{{ item }}"
        admins: "{{ args.admins }}"
      with_items:
        - "{{ args.users }}"