---

- name: "Refresh jail"
  command: autoweb_refresh_jail
  
- name: "Restart apache2"
  service:
    name: apache2
    state: restarted

- name: "Restart bind9"
  service:
    name: bind9
    state: restarted