
- name: "remove user"
  user:
    name: "{{ user.unix_username }}"
    home: "{{ configs.chroot_path }}/./home/{{ user.unix_username }}"
    shell: "/usr/sbin/jk_chrootsh"
    state: absent
  notify: Refresh jail

- name: "remove user's group"
  ansible.builtin.group:
    name: "{{ user.unix_username }}"
    state: absent
  notify: Refresh jail

- name: "Ensure user.unix_username is safe"
  assert:
    that:
      - user.unix_username is defined
      - user.unix_username | trim | length > 0
      - user.unix_username not in ['.', '..']
    fail_msg: "user.unix_username empty or invalid"

- name: "remove {{ configs.chroot_path }}/home/{{ user.unix_username }}"
  file:
    path: "{{ configs.chroot_path }}/home/{{ user.unix_username }}"
    state: absent
  when:
    - user.unix_username is defined
    - user.unix_username | trim | length > 0
    - user.unix_username != '.'
    - user.unix_username != '..'
