---

- name: "Install bind9"
  apt:
    name: bind9
    state: present
  notify: Restart bind9

- name: "Copy dns conf"
  copy:
    src: "files/dns/"
    dest: "/etc/bind/"
    owner: root
    group: root
    mode: 0755
  notify: Restart bind9

- name: "Mkdir /etc/bind/zones.autoweb"
  file:
    path: "/etc/bind/zones.autoweb"
    state: directory

- name: "Mkdir /var/lib/bind/zones.autoweb"
  file:
    path: "/var/lib/bind/zones.autoweb"
    owner: root
    group: bind
    mode: 0775
    state: directory

- name: "Copy services conf"
  template:
    src: "templates/dns/services.j2"
    dest: "/etc/bind/zones.autoweb/services"
    owner: root
    group: root
    mode: 0644
  notify: Restart bind9

- name: "Copy pri.phpmyadmin"
  template:
    src: "templates/dns/pri.zone.phpmyadmin.j2"
    dest: "/etc/bind/zones.autoweb/pri.phpmyadmin"
    owner: root
    group: root
    mode: 0644
  notify: Restart bind9

- name: "Copy pri.autoweb"
  template:
    src: "templates/dns/pri.zone.autoweb.j2"
    dest: "/var/lib/bind/zones.autoweb/pri.autoweb"
    owner: root
    group: bind
    mode: 0664
  notify: Restart bind9

- name: "Mkdir /etc/bind/zones.autoweb/master.fragments"
  file:
    path: "/etc/bind/zones.autoweb/master.fragments"
    state: directory

- name: "touch /etc/bind/zones.autoweb/master"
  file:
    path: "/etc/bind/zones.autoweb/master"
    state: touch

- name: "Generate HMAC key for Bind9"
  shell:
    cmd: "tsig-keygen -a HMAC-SHA512 letsencrypt_wildcard > /etc/bind/letsencrypt_wildcard.key"
    creates: /etc/bind/letsencrypt_wildcard.key
  notify: Restart bind9

- name: "Start service bind9"
  service:
    name: bind9
    state: started
    enabled: yes
